### ISSUE TITLE
Add Dependabot

### ISSUE THREAD

**Issue by steinbrueckri** [S-Sergej/pLanComm#43]
Hi!
I saw in PullRequest #42 that you manually updated dependencies. I think it would make sense to enable dependabot for the project so you don't have to do it yourself anymore ;)

Cheers Richard 🍻

**Comment by steinbrueckri** [comment]
#45

**Comment by S-Sergej** [comment]
> Hi!
> I saw in PullRequest #42 that you manually updated dependencies. I think it would make sense to enable dependabot for the project so you don't have to do it yourself anymore ;)
> 
> Cheers Richard 🍻

Thx Richard. Its worth an invitation for a Beer ;)
